apiVersion: v1
kind: Service
metadata:
  name: html-resume-service
spec:
  selector:
    app: html-resume
  ports:
    - protocol: TCP
      port: 80  # External port to expose
      targetPort: 80 # Port of the container
  type: LoadBalancer # For external access (adjust if needed)
