name: Build, Push, and Deploy to Kubernetes

on: 
  push:
    branches: [ main ]  
  pull_request:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Deploy to Kubernetes
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
        env: 
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }} 
          IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: |
          npm install -g kubectl
          kubectl apply -f deployment.yaml
